import { ExperienceSection } from "@/components/sections/home/Experience";
import { HeroSection } from "@/components/sections/home/Hero";
import { HighlightedSection } from "@/components/sections/home/Highlighted";
import { TechSection } from "@/components/sections/home/Technology";

export const metadata = {
  title: "My Portfolio | Home",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main>
      <HeroSection />
      <TechSection />
      <HighlightedSection />
      <ExperienceSection />
    </main>
  );
}
