import { ExperienceSection } from "@/components/sections/home/Experience";
import { HeroSection } from "@/components/sections/home/Hero";
import { HighlightedSection } from "@/components/sections/home/Highlighted";
import { TechSection } from "@/components/sections/home/Technology";
import { fetchHygraphQuery } from "@/utils/hygraph-fetch";
import { GET_HOME } from "@/utils/hygraph-queries";

export const metadata = {
  title: "Home",
  description: "Generated by create next app",
};

const getHomeData = async (): Promise<IHomePage> => {
  return fetchHygraphQuery(GET_HOME, 60);
};

export default async function Home() {
  const { home, experiences } = await getHomeData();

  return (
    <main>
      <HeroSection pageInfo={home} />
      <TechSection techInfo={home.skills} />
      <HighlightedSection projects={home.highlightProjects} />
      <ExperienceSection experiences={experiences} />
    </main>
  );
}
