import { HeroSection } from "@/components/sections/project/Hero";
import { ProjectListSection } from "@/components/sections/project/ProjectList";

export const metadata = {
  title: "My Portfolio | Portfolio",
  description: "Generated by create next app",
};

export default function Projects() {
  return (
    <main>
      <HeroSection />
      <ProjectListSection />
    </main>
  );
}
