export const metadata = {
  title: "My Portfolio | Portfolio",
  description: "Generated by create next app",
};

export default function Project() {
  return (
    <main>
      <div>Project</div>
    </main>
  );
}
