import { HeroSection } from "@/components/sections/project/Hero";
import { ProjectListSection } from "@/components/sections/project/ProjectList";
import { fetchHygraphQuery } from "@/utils/hygraph-fetch";
import { GET_PROJECTS } from "@/utils/hygraph-queries";

export const metadata = {
  title: "Projeto",
  description: "Generated by create next app",
};

const getProjectData = async (): Promise<IProjectsPage> => {
  return fetchHygraphQuery(GET_PROJECTS, 60);
};

export default async function Projects() {
  const { projects } = await getProjectData();

  return (
    <main>
      <HeroSection />
      <ProjectListSection projects={projects} />
    </main>
  );
}
